### ISSUE TITLE
[enhancement] Adding Fedora Rawhide support

### ISSUE THREAD

**Issue by manero6** [audinux/audinux.github.io#5]
Hi, first of all I'm very happy with this COPR repo.  
It has many packages that I like, especially Rack-v1 and Rack-v2 :)

I was using this repo on a Fedora 38 laptop without any issues.  
Now I switched laptop and I decided to go for Fedora Rawhide (which right now is Fedora 40), and when trying to add this repo I get and error, as there is no Rawhide support yet.

Do you plan to add Rawhide support too for this repo?

Cheers

**Comment by ycollet** [comment]
Thanks for this message !
For eawhide: the problem is things are changing a little bit too fast and will trigger rebuild of many packages.
I have a project to do a build for a centos version. So that we can have a more "long term" distribution to work with.
In the mean time, I will start the build for Fedora 39 once Fedora 39 will switch to beta. I beta, binary things are frozen and I can safely build things ...

**Comment by ycollet** [comment]
I activated the rawhide repo. I will start filling this repo when Fedora 40 beta will be out.

**Comment by ycollet** [comment]
Done
